title: Remote France
description: Quelle ville française choisir pour le télétravail ?
show_downloads: true
google_analytics: UA-129160412-1
theme: jekyll-theme-cayman

gems:
  - jekyll-paginate-v2

pagination:
  enabled: true
  per_page: 5
  permalink: '/page/:num/'
  sort_field: 'date'
  sort_reverse: true

permalink: /:year/:month/:title.html

include: ['_redirects']

## I18N
languages: ["en", "fr"]
exclude_from_localizations: ["assets", "CNAME"]
defaultLang: fr
languageNames:
  fr: Français
  en: English

  
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
